const config = {
  APP_ENV: window.APP_CONFIG?.APP_ENV || process.env.REACT_APP_ENV,
  APP_ACCESS_KEY_ID: window.APP_CONFIG?.APP_ACCESS_KEY_ID || process.env.REACT_APP_ACCESS_KEY_ID,
  APP_SECRET_ACCESS_KEY: window.APP_CONFIG?.APP_SECRET_ACCESS_KEY || process.env.REACT_APP_SECRET_ACCESS_KEY,
  APP_REGION: window.APP_CONFIG?.APP_REGION || process.env.REACT_APP_REGION,
  APP_BUCKET_TEMP: window.APP_CONFIG?.APP_BUCKET_TEMP || process.env.REACT_APP_BUCKET_TEMP,
  APP_PROD_BUCKET: window.APP_CONFIG?.APP_PROD_BUCKET || process.env.REACT_APP_PROD_BUCKET,
  APP_S3_DOMAIN: window.APP_CONFIG?.APP_S3_DOMAIN || process.env.REACT_APP_S3_DOMAIN,
  APP_PROD_FOLDER: window.APP_CONFIG?.APP_PROD_FOLDER || process.env.REACT_APP_PROD_FOLDER,
  APP_FIREBASE_API_KEY: window.APP_CONFIG?.APP_FIREBASE_API_KEY || process.env.REACT_APP_FIREBASE_API_KEY,
  APP_AUTH_DOMAIN: window.APP_CONFIG?.APP_AUTH_DOMAIN || process.env.REACT_APP_AUTH_DOMAIN,
  APP_PROJECTID: window.APP_CONFIG?.APP_PROJECTID || process.env.REACT_APP_PROJECTID,
  APP_STORAGE_BUCKET: window.APP_CONFIG?.APP_STORAGE_BUCKET || process.env.REACT_APP_STORAGE_BUCKET,
  APP_MESSAGING_SENDER_ID: window.APP_CONFIG?.APP_MESSAGING_SENDER_ID || process.env.REACT_APP_MESSAGING_SENDER_ID,
  APP_APPID: window.APP_CONFIG?.APP_APPID || process.env.REACT_APP_APPID,
  APP_HOST: window.APP_CONFIG?.APP_HOST || process.env.REACT_APP_HOST
}

export default config;